export const propertiesData = {
  /* ─── À VENDRE ─── */
  1: {
    id: 1,
    title: "Villa Moderne avec Piscine",
    price: "150 000 000",
    priceUnit: "FCFA",
    status: "À Vendre",
    location: "Sablière, Libreville, Gabon",
    beds: 5,
    baths: 4,
    surface: 350,
    type: "Villa",
    parking: "2 Places",
    image: "/images/villa-piscine-1.jpg.png",
    image2: "/images/villa-piscine-2.jpg.png",
    description:
      "Magnifique villa contemporaine située dans le quartier très prisé de la Sablière. Offrant de très belles prestations, cette propriété dispose d'un vaste salon lumineux avec vue sur la piscine à débordement, une cuisine américaine entièrement équipée, et 5 chambres spacieuses dont une suite parentale avec dressing et salle de bain privative. Le jardin paysager vous garantit intimité et calme absolu.",
    amenities: [
      "Piscine privée",
      "Climatisation",
      "Jardin paysager",
      "Garage sécurisé",
      "Cuisine équipée",
      "Système d'alarme",
      "Terrasse",
      "Vue dégagée",
    ],
  },
  2: {
    id: 2,
    title: "Appartement de Luxe Vue Mer",
    price: "85 000 000",
    priceUnit: "FCFA",
    status: "À Vendre",
    location: "Batterie IV, Libreville, Gabon",
    beds: 3,
    baths: 2,
    surface: 180,
    type: "Appartement",
    parking: "1 Place",
    image: "/images/apartment1.png",
    description:
      "Superbe appartement de standing au cœur du quartier Batterie IV, offrant une vue panoramique sur l'Atlantique. Entièrement rénové avec des matériaux haut de gamme, il comprend un séjour ouvert sur la mer, une cuisine équipée dernier cri, et trois chambres lumineuses. La résidence sécurisée 24h/24 dispose d'un ascenseur et d'un parking privatif.",
    amenities: [
      "Vue sur mer",
      "Climatisation",
      "Ascenseur",
      "Parking privatif",
      "Cuisine équipée",
      "Résidence sécurisée",
      "Balcon",
      "Gardiennage 24h",
    ],
  },
  3: {
    id: 3,
    title: "Résidence Contemporaine",
    price: "220 000 000",
    priceUnit: "FCFA",
    status: "À Vendre",
    location: "Akanda, Libreville, Gabon",
    beds: 3,
    baths: 2,
    surface: 420,
    type: "Immeuble",
    parking: "6 Places",
    image: "/images/residence-contemporaine-1.jpg.png",
    image2: "/images/residence-contemporaine-2.jpg.png",
    description:
      "Immeuble résidentiel de standing situé à Akanda, quartier prisé de Libreville. Cet immeuble contemporain R+2 propose des appartements haut de gamme aux finitions soignées : larges baies vitrées, cuisine américaine en marbre, plafonds à caissons avec éclairage LED intégré et terrasses privatives à chaque étage. La façade en bois et verre confère à l'ensemble une esthétique architecturale rare sur le marché gabonais.",
    amenities: [
      "Appartements haut de gamme",
      "Baies vitrées panoramiques",
      "Terrasses privatives",
      "Cuisine en marbre équipée",
      "Éclairage LED intégré",
      "Parking sécurisé 6 places",
      "Groupe électrogène",
      "Système d'alarme avancé",
    ],
  },
  4: {
    id: 4,
    title: "Appartement Centre-Ville",
    price: "45 000 000",
    priceUnit: "FCFA",
    status: "À Vendre",
    location: "Centre-Ville, Libreville, Gabon",
    beds: 2,
    baths: 1,
    surface: 90,
    type: "Appartement",
    parking: "1 Place",
    image: "/images/apartment1.png",
    description:
      "Appartement fonctionnel et bien agencé en plein cœur de Libreville, idéal pour un premier achat ou un investissement locatif. À deux pas des commerces, administrations et restaurants, il offre une vie pratique au quotidien avec deux chambres confortables, un séjour lumineux et une cuisine semi-équipée.",
    amenities: [
      "Emplacement central",
      "Climatisation",
      "Parking",
      "Proximité commerces",
      "Cuisine semi-équipée",
      "Gardiennage",
      "Interphone",
      "Balcon",
    ],
  },
  5: {
    id: 5,
    title: "Villa Familiale",
    price: "110 000 000",
    priceUnit: "FCFA",
    status: "À Vendre",
    location: "Angondjé, Libreville, Gabon",
    beds: 4,
    baths: 3,
    surface: 280,
    type: "Villa",
    parking: "2 Places",
    image: "/images/villa1.png",
    description:
      "Belle villa familiale dans le quartier résidentiel d'Angondjé, prisé pour son calme et sa sécurité. La propriété dispose d'un grand jardin arboré, d'un spacieux salon-séjour, d'une cuisine équipée ouverte sur la terrasse, et de quatre chambres dont une suite parentale. Idéale pour une famille cherchant un cadre de vie agréable.",
    amenities: [
      "Grand jardin",
      "Terrasse couverte",
      "Climatisation",
      "Cuisine équipée",
      "Garage double",
      "Quartier sécurisé",
      "Eau chaude solaire",
      "Espace barbecue",
    ],
  },
  6: {
    id: 6,
    title: "Terrain Constructible",
    price: "35 000 000",
    priceUnit: "FCFA",
    status: "À Vendre",
    location: "Cap Estérias, Libreville, Gabon",
    beds: 0,
    baths: 0,
    surface: 1000,
    type: "Terrain",
    parking: "—",
    image: "/images/terrain-constructible-1.jpg.png",
    image2: "/images/terrain-constructible-2.jpg.png",
    description:
      "Terrain constructible de 1 000 m² situé à Cap Estérias, zone en plein essor à proximité de la mer. Le terrain est viabilisé (eau, électricité en bordure), plat et clôturé. Un investissement stratégique dans une zone à fort potentiel de valorisation, idéal pour la construction d'une villa ou d'un petit immeuble résidentiel.",
    amenities: [
      "Terrain plat et clôturé",
      "Viabilisé (eau & électricité)",
      "Accès route bitumée",
      "Proche du littoral",
      "Titre foncier disponible",
      "Zone résidentielle",
    ],
  },

  7: {
    id: 7,
    title: "Immeuble R+2 en Construction",
    price: "180 000 000",
    priceUnit: "FCFA",
    status: "Programme Neuf",
    location: "Angondjé, Libreville, Gabon",
    beds: 0,
    baths: 0,
    surface: 800,
    type: "Immeuble",
    parking: "10 Places",
    image: "/images/immeuble-chantier-1.jpg.jpg",
    image2: "/images/immeuble-chantier-2.jpg.jpg",
    image3: "/images/immeuble-chantier-3.jpg.jpg",
    description:
      "Programme immobilier d'exception en cours de réalisation à Angondjé, l'un des quartiers les plus dynamiques de Libreville. Cet immeuble R+2 de 800 m² habitables offre des plateaux modulables pouvant accueillir des bureaux, commerces ou appartements résidentiels. La structure en béton armé est déjà coulée et les finitions démarrent au T3 2026. Un investissement stratégique à saisir dès la phase chantier pour bénéficier du meilleur prix.",
    amenities: [
      "Structure béton armé R+2",
      "Plateaux modulables",
      "Façade vitrée architecturale",
      "Parking 10 places",
      "Livraison T4 2026",
      "Titre foncier disponible",
      "Accès voie bitumée",
      "Quartier en plein essor",
    ],
  },

  /* ─── À LOUER ─── */
  10: {
    id: 10,
    title: "Appartement Meublé Haut Standing",
    price: "350 000",
    priceUnit: "FCFA / mois",
    status: "À Louer",
    location: "Batterie IV, Libreville, Gabon",
    beds: 3,
    baths: 2,
    surface: 160,
    type: "Appartement",
    parking: "1 Place",
    image: "/images/apartment1.png",
    description:
      "Appartement entièrement meublé et équipé dans une résidence sécurisée de Batterie IV. Idéal pour expatriés ou cadres, il intègre un salon moderne, une cuisine américaine équipée, trois chambres confortables et deux salles de bain. Prêt à vivre, avec toute la vaisselle, la literie et les équipements électroménagers inclus.",
    amenities: [
      "Entièrement meublé",
      "Cuisine équipée",
      "Climatisation",
      "Résidence sécurisée",
      "Parking privatif",
      "Wifi inclus",
      "Ascenseur",
      "Balcon vue mer",
    ],
  },
  11: {
    id: 11,
    title: "Villa avec Jardin Privatif",
    price: "800 000",
    priceUnit: "FCFA / mois",
    status: "À Louer",
    location: "Sablière, Libreville, Gabon",
    beds: 5,
    baths: 4,
    surface: 320,
    type: "Villa",
    parking: "2 Places",
    image: "/images/villa1.png",
    description:
      "Magnifique villa indépendante à louer dans l'un des quartiers les plus recherchés de Libreville. Avec son vaste jardin privatif, sa piscine, et ses prestations haut de gamme, cette propriété offre un cadre de vie exceptionnel pour les familles ou les expatriés exigeants. Disponible immédiatement.",
    amenities: [
      "Piscine privée",
      "Jardin privatif",
      "Climatisation centrale",
      "Cuisine équipée",
      "Garage double",
      "Système d'alarme",
      "Gardien",
      "Groupe électrogène",
    ],
  },
  12: {
    id: 12,
    title: "Résidence Sécurisée Vue Mer",
    price: "550 000",
    priceUnit: "FCFA / mois",
    status: "À Louer",
    location: "Akanda, Libreville, Gabon",
    beds: 4,
    baths: 3,
    surface: 220,
    type: "Appartement",
    parking: "1 Place",
    image: "/images/hero.png",
    description:
      "Appartement spacieux en résidence fermée à Akanda avec une vue imprenable sur l'Atlantique. Lumineux et bien ventilé, il comprend quatre chambres, trois salles de bain, un grand salon ouvrant sur une terrasse panoramique. Résidence avec gardiennage 24h, piscine commune et accès plage à pied.",
    amenities: [
      "Vue sur mer",
      "Terrasse panoramique",
      "Piscine commune",
      "Accès plage",
      "Gardiennage 24h",
      "Climatisation",
      "Parking couvert",
      "Cuisine équipée",
    ],
  },
  13: {
    id: 13,
    title: "Studio Moderne Centre-Ville",
    price: "180 000",
    priceUnit: "FCFA / mois",
    status: "À Louer",
    location: "Centre-Ville, Libreville, Gabon",
    beds: 1,
    baths: 1,
    surface: 55,
    type: "Studio",
    parking: "—",
    image: "/images/apartment1.png",
    description:
      "Studio moderne et fonctionnel en plein centre de Libreville, idéal pour un étudiant, un jeune professionnel ou une personne seule en déplacement. Entièrement meublé avec goût, il offre un espace de vie optimisé avec kitchenette équipée et salle de bain moderne. Accès immédiat aux commerces, restaurants et transports.",
    amenities: [
      "Entièrement meublé",
      "Kitchenette équipée",
      "Climatisation",
      "Immeuble sécurisé",
      "Interphone",
      "Proche transports",
      "Internet disponible",
      "Eau chaude",
    ],
  },
  14: {
    id: 14,
    title: "Appartement Familial Spacieux",
    price: "420 000",
    priceUnit: "FCFA / mois",
    status: "À Louer",
    location: "Angondjé, Libreville, Gabon",
    beds: 4,
    baths: 2,
    surface: 190,
    type: "Appartement",
    parking: "1 Place",
    image: "/images/villa1.png",
    description:
      "Grand appartement familial dans la résidence Le Palais d'Angondjé, quartier calme et verdoyant. Avec ses quatre chambres, son double séjour et sa cuisine aménagée, il convient parfaitement à une famille à la recherche de confort et d'espace. La résidence dispose d'un espace vert commun et d'une sécurité renforcée.",
    amenities: [
      "Grand séjour double",
      "Cuisine aménagée",
      "Climatisation",
      "Espace vert commun",
      "Parking couvert",
      "Sécurité 24h",
      "Buanderie",
      "Quartier calme",
    ],
  },
  15: {
    id: 15,
    title: "Villa Contemporaine Climatisée",
    price: "1 200 000",
    priceUnit: "FCFA / mois",
    status: "À Louer",
    location: "Cap Estérias, Libreville, Gabon",
    beds: 6,
    baths: 5,
    surface: 450,
    type: "Villa",
    parking: "3 Places",
    image: "/images/hero.png",
    description:
      "Villa de prestige à louer à Cap Estérias, dans un environnement paisible en bord de mer. Cette propriété d'exception de 450 m² dispose de 6 suites climatisées, d'un salon de réception, d'une cuisine professionnelle, d'une piscine à débordement et d'un jardin tropical soigné. Idéale pour une grande famille ou une résidence de représentation.",
    amenities: [
      "Piscine à débordement",
      "Climatisation centrale",
      "Cuisine professionnelle",
      "Jardin tropical",
      "Garage triple",
      "Système domotique",
      "Groupe électrogène",
      "Vue mer",
    ],
  },
};
